### ISSUE TITLE
Getting below error

### ISSUE THREAD

**Issue by rahulcse1** [craigburke/google-calendar-grails#8]
Property org.springframework.context.support.DefaultMessageSourceResolvable: codes [org.osw.event.Events.startTime,startTime]; arguments []; default message [startTime] must be a valid Date

-------
I am not sure why am i getting this ? any thought ?

**Comment by craigburke** [comment]
@rahulcse1 I'm not sure. I haven't really looked at this project in years and the version of Grails it uses is pretty old. 

If you figure it out feel free to submit a PR, but I don't think I'll be doing any updates to this project in the foreseeable future.
